version: "3"
services:
  recipiy:
    container_name: "recipiy"
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    volumes:
      - ./dockervenv:/.venv
      - .:/app
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
